# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IgnoreThis' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for IgnoreThis

  target 'IgnoreThisTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'OCMock', '~> 3.4' 
  end

  target 'IgnoreThisUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
