# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.97.2"

default_platform :ios



platform :ios do
  before_all do
    cocoapods
  end

  desc "Run unit tests on all simulators"
  lane :unit_test do |options|
    scan(
      scheme: 'IgnoreThis',
      devices: ['iPhone 7 Plus']
    )
    xcov(
      scheme: 'IgnoreThis',
      output_directory: 'fastlane/code_coverage'
    )
  end
end